[features]
seeds = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy = "cp -r ./target/idl ./src/"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
voting = "AAFLi32KG5XDdfcJUEjHnQFCghQfusX4pbqtYaivv7DE"

[registry]
url = "https://anchor.projectserum.com"


