[features]
seeds = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy = "cp -r ./target/idl ./src/"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.localnet]
voting = "Fx2TKLRC5V8Xu6R1w42C6k7NUXr35qVudXX86jk6RVky"

[registry]
url = "https://anchor.projectserum.com"

[test]
startup_wait = 10000


